# 1 Write a program to perform arithmetic operations
a, b = input("Enter Two Numbers: ").split()
a = int(a)
b = int(b)
print("A: " + str(a))
print("B: " + str(b))
print("ADD: " + str(a+b))
print("SUB: " + str(a-b))
print("MUL: " + str(a*b))
print("DIV: " + str(a/b))
